#!/bin/bash

echo 'Need sudo for adding yarn and neovim-nightly repo'

sudo curl -sL https://dl.yarnpkg.com/rpm/yarn.repo -o /etc/yum.repos.d/yarn.repo
sudo dnf copr -y enable agriffis/neovim-nightly
