#!/bin/bash

echo 'Need sudo for adding repos'

# install yarn repo
sudo curl -sL https://dl.yarnpkg.com/rpm/yarn.repo -o /etc/yum.repos.d/yarn.repo

# install i3status-rust repo
sudo dnf copr -y enable atim/i3status-rust

# install neovim-nightly repo
sudo dnf copr -y enable agriffis/neovim-nightly

# install lazygit repo
sudo dnf copr -y enable atim/lazygit -y

# install rpm fusion free repo and sound-and-video group
sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf groupupdate sound-and-video

# install patched font
mkdir /tmp/Inconsolata
cd /tmp/Inconsolata/
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Inconsolata.zip
unzip Inconsolata.zip
rm Inconsolata.zip
rm -vrf -- *Compatible*
mv /tmp/Inconsolata ~/.local/share/fonts/

sudo dnf install -y gnome-tweaks keepassxc \
  ncurses-devel automake autoconf gcc # deps for htop-vim

# install nemo
sudo dnf install -y nemo nemo-audio-tab nemo-compare nemo-emblems nemo-extensions nemo-fileroller nemo-image-converter nemo-preview nemo-seahorse nemo-search-helpers
xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search
gsettings set org.gnome.desktop.background show-desktop-icons false
gsettings set org.nemo.desktop show-desktop-icons true

## install vscode
# sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
# cat <<EOF | sudo tee /etc/yum.repos.d/vscode.repo
# [code]
# name=Visual Studio Code
# baseurl=https://packages.microsoft.com/yumrepos/vscode
# enabled=1
# gpgcheck=1
# gpgkey=https://packages.microsoft.com/keys/microsoft.asc
# EOF
